name: Generate Isometric Contributions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Isometric 3D Calendar
        uses: jasonlong/github-isometric-contributions@main
        with:
          user_name: FiasaScript
          theme: github-dark

      - name: Push image to repository
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
