name: Generate Isometric Contributions

on:
  # Roda automaticamente a cada 24 horas
  schedule:
    - cron: "0 0 * * *"
  # Permite que você rode manualmente quando quiser
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Isometric 3D Calendar
        uses: jasonlong/github-isometric-contributions@v1.4
        with:
          user_name: FiasaScript
          # Você pode escolher o tema: "classic" (verde GitHub) ou "github-dark" (combina com seu setup)
          theme: github-dark

      - name: Push image to repository
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
